import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import AuthContextProvider from "./lib/contexts/AuthContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blog Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <Header />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}